---
nginx-ingress:
  controller:
    appprotect:
      enable: true
    appprotectdos:
      enable: true
    enableSnippets: true
    image:
      repository: ghcr.io/w-owens/nginx-plus-ingress
      tag: 2.3.0-SNAPSHOT-979db22
    nginxplus: true
    nginxStatus:
      allowCidrs: 0.0.0.0/0
      port: 9000
    serviceAccount:
      imagePullSecretName: ghcr
  prometheus:
    create: true
